# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

hidden_imports = [
    # PyQt6
    "PyQt6",
    "PyQt6.QtWidgets",
    "PyQt6.QtCore",
    "PyQt6.QtGui",
    "PyQt6.QtPrintSupport",
    "PyQt6.sip",

    # matplotlib
    "matplotlib",
    "matplotlib.backends.backend_qtagg",
    "matplotlib.backends.backend_agg",
    "matplotlib.figure",
    "matplotlib.pyplot",
    "matplotlib.patches",
    "matplotlib.lines",

    # sentence transformers + transformers
    "sentence_transformers",
    "sentence_transformers.models",
    "sentence_transformers.losses",
    "sentence_transformers.datasets",
    "transformers",
    "transformers.models",
    "transformers.models.bert",
    "transformers.pipelines",
    "tokenizers",
    "huggingface_hub",
    "huggingface_hub.file_download",

    # torch
    "torch",
    "torch.nn",
    "torch.nn.functional",
    "torch.utils",
    "torch.utils.data",

    # numpy / scipy / sklearn
    "numpy",
    "numpy.core",
    "numpy.core._multiarray_umath",
    "scipy",
    "scipy.spatial",
    "scipy.spatial.distance",
    "sklearn",
    "sklearn.metrics",
    "sklearn.metrics.pairwise",
    "sklearn.preprocessing",
    "sklearn.decomposition",

    # nltk (pulled in by sentence-transformers)
    "nltk",
    "nltk.tokenize",
    "nltk.corpus",
    "nltk.stem",
    "nltk.metrics",
    "nltk.metrics.scores",
    "nltk.collocations",
    "nltk.util",

    # standard library essentials
    "pickle",
    "pydoc",
    "doctest",
    "inspect",
    "pprint",
    "multiprocessing",
    "multiprocessing.pool",
    "multiprocessing.managers",
    "concurrent.futures",
    "threading",
    "queue",
    "json",
    "sqlite3",
    "pathlib",
    "datetime",
    "logging",
    "copy",
    "re",
    "os",
    "sys",
    "io",
    "struct",
    "typing",
    "abc",
    "enum",
    "functools",
    "itertools",
    "collections",
    "contextlib",
    "warnings",
    "traceback",
    "inspect",
    "platform",
    "importlib",
    "importlib.metadata",
    "importlib.resources",
    "importlib.util",
    "codecs",
    "encodings",
    "encodings.utf_8",
    "encodings.ascii",
    "encodings.latin_1",

    # networking
    "requests",
    "requests.adapters",
    "requests.auth",
    "requests.models",
    "requests.sessions",
    "urllib3",
    "urllib3.util",
    "urllib3.util.retry",
    "certifi",
    "charset_normalizer",
    "idna",

    # utilities
    "tqdm",
    "tqdm.auto",
    "tqdm.notebook",
    "packaging",
    "packaging.version",
    "packaging.requirements",
    "filelock",
    "fsspec",
    "regex",
    "PIL",
    "PIL.Image",
    "PIL.ImageDraw",
    "PIL.ImageFont",

    # sqlalchemy
    "sqlalchemy",
    "sqlalchemy.dialects",
    "sqlalchemy.dialects.sqlite",
    "sqlalchemy.pool",
    "sqlalchemy.orm",

    # app modules
    "app",
    "app.db",
    "app.db.database",
    "app.db.importer",
    "app.ai",
    "app.ai.embedder",
    "app.ai.rag_engine",
    "app.ui",
    "app.ui.main_window",
    "app.ui.dashboard_tab",
    "app.ui.transactions_tab",
    "app.ui.compare_tab",
    "app.ui.chat_tab",
    "app.ui.settings_tab",
    "app.settings",
]

a = Analysis(
    ["main.py"],
    pathex=["."],
    binaries=[],
    datas=[
        ("data",   "data"),
        ("assets", "assets"),
        ("app",    "app"),
    ],
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "tkinter.ttk",
        "_tkinter",
        "ipython",
        "IPython",
        "jupyter",
        "jupyter_client",
        "jupyter_core",
        "notebook",
        "nbformat",
        "nbconvert",
        "pytest",
        "setuptools",
        "distutils",
        "lib2to3",
        "test",
        "tests",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="FinanceTracker",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    icon="assets/icon.ico",
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="FinanceTracker",
)